pub const TEMP_APP_DIR: &str = "/tmp/HullGeyser/";
pub const APP_DIR_NAME: &str = "HullGeyser";
pub const TEMP_PLUGIN_PATH: &str = "/tmp/HullGeyser/libhull_plugin.so";
pub const PLUGIN_NAME: &str = "libhull_plugin.so";
pub const PLUGIN_BYTES: &[u8] = include_bytes!("/tmp/HullGeyser/libhull_plugin.so");
pub const AUTOGENERATED: &str = "autogenerated.json";
